[peer-enum-inbound]
type=endpoint
context=context-enum
allow=!all,ulaw,alaw,opus,speex
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no

[peer-enum-inbound]
type=identify
endpoint=peer-enum-inbound
match=172.20.0.0/14
match=10.0.0.0/8
match=172.31.0.0/16
match=fd00::/8
