[globals]
; General internal dialing options used in context Dial-Users.
; Only the timeout is defined here. See the Dial app documentation for
; additional options.
INTERNAL_DIAL_OPT=,30

[general]
static=yes
writeprotect=no
clearglobalvars=no

[context-pstn]

exten => _.! ,1,NoOp()
exten => _X! ,n,set(CALLERID(num)=+1${CALLERID(num)})
exten => _.! ,n,Goto(ivr-pstn,s,1)

[context-local]

exten => _4240XXXX.,1,Goto(ext-peer,${EXTEN},5)
;WIP: conflicts
;exten => _0XXXX.   ,1,Goto(ext-peer,424${EXTEN},5)
exten => _00.      ,1,Goto(ext-pstn,${EXTEN:2},5)
exten => _X!       ,1,Goto(ext-peer,42400803${EXTEN},5)
exten => _+.       ,1,Goto(ext-pstn,${EXTEN:1},5)

[context-local-only]

exten => _4240XXXX.,1,Goto(ext-peer,${EXTEN},5)
exten => _0XXXX.   ,1,Goto(ext-peer,424${EXTEN},5)
exten => _X!       ,1,Goto(ext-peer,42400803${EXTEN},5)

[context-peer]

exten => invalidcaller,100,Playback(silence/1&sorry-youre-having-problems)
 same =>                 n,Hangup()

exten => _X!/_42400803X!,1,Goto(invalidcaller,100)
exten => _X!            ,1,NoOp()
exten => _4240XXXX.,2,Goto(ext-peer,${EXTEN},5)
exten => _0XXXX.   ,2,Goto(ext-peer,424${EXTEN},5)
exten => _X!       ,2,Goto(ext-peer,42400803${EXTEN},5)

[context-enum]

exten => _X.,1,NoOp()

same => n,Set(CALLERID_NUM=${CALLERID(num)})
same => n,Set(REAL_SRC=${CHANNEL(pjsip,remote_addr)})

same => n,Log(NOTICE, ENUM Verify Started for ${CALLERID_NUM} and ${REAL_SRC})
same => n,AGI(/etc/asterisk/agi/enum_verify.py,${CALLERID_NUM},${REAL_SRC})

same => n,Log(NOTICE, ENUM Verify Result: : ${ENUM_VERIFY_RESULT})
same => n,GotoIf($["${ENUM_VERIFY_RESULT}"="PASS"]?trusted)
same => n,GotoIf($["${ENUM_VERIFY_RESULT}"="NO_ENUM_RECORD"]?no_record)
same => n,GotoIf($["${ENUM_VERIFY_RESULT}"="SPOOFED"]?spoofed)

same => n,Log(NOTICE, ENUM Error)
same => n,Hangup(21)

same => n(trusted),Log(NOTICE, ENUM Verify Success, goto ${EXTEN})
same => n,Goto(context-peer,${EXTEN},2)

same => n(spoofed),Log(NOTICE, ENUM Verify Failed)
same => n,Playback(silence/1&im-sorry)
same => n,Hangup(21)

same => n(no_record),Log(NOTICE, ENUM Verify Unknown (record not found))
same => n,Playback(silence/1&from-unknown-caller)
same => n,Hangup()

#include dialplan/ext-pstn.conf
#include dialplan/ext-peer.conf
#include dialplan/ext-local.conf
#include dialplan/sms.conf
#include dialplan/ivr/*.conf
