[general]
tlsenable=yes
tlsbindaddr=[::]:8089
tlscertfile=/var/lib/caddy/.local/share/caddy/certificates/acme.burble.dn42-v1-dn42-acme-directory/pbx.gensokyo.dn42/pbx.gensokyo.dn42.crt
tlsprivatekey=/var/lib/caddy/.local/share/caddy/certificates/acme.burble.dn42-v1-dn42-acme-directory/pbx.gensokyo.dn42/pbx.gensokyo.dn42.key
