[fax1]
type=friend
username=fax1
secret=31415926535
auth=md5
host=dynamic
context=context-local
callerid=Fax Modem <424008034001>
requirecalltoken=no

[fax2]
type=friend
username=fax2
secret=31415926535
auth=md5
host=dynamic
context=context-local
callerid=Fax Modem <424008034002>
requirecalltoken=no
