[webdemo](webrtc-template-aor)
max_contacts=3

[webdemo](webrtc-template-endpoint)
auth = webdemo
aors = webdemo
callerid=WebRTC Demo <424008039910>
context=context-local-only

[webdemo](webrtc-template-auth)
auth_type=userpass
username=webdemo
password=webdemo
