[ext-invalid]

exten => i,5,Goto(invalidinput,5)
exten => t,5,Hangup()

exten => NOANSWER,5,Playback(silence/1&number-not-answering&please-try-call-later&silence/1)
 same => n,Hangup()

exten => BUSY,5,Playback(silence/1&the-party-you-are-calling&is-curntly-busy&silence/1)
 same => n,Hangup()

exten => CHANUNAVAIL,5,Playback(silence/1&im-sorry&number-not-answering&please-try-call-later&silence/1)
 same => n,Hangup()

exten => CONGESTION,5,Playback(silence/1&all-circuits-busy-now&please-try-call-later&silence/1)
 same => n,Hangup()

exten => CANCEL,5,Hangup()
exten => ANSWER,5,Hangup()

exten => unallocated,5,Playback(silence/1&im-sorry&the-number-u-dialed&is-unallocated&silence/1)
 same => n,Hangup()

exten => invalidinput,5,Playback(silence/1&im-sorry&cannot-complete-as-dialed&check-number-dial-again&silence/1)
 same => n,Hangup()

; fallbacks
exten => _X!,5,Goto(invalidinput,5)
exten => _+X!,5,Goto(invalidinput,5)
