[ext-local]

exten => i,1,NoOp()

exten => fax,1,Queue(faxs)

exten => chanunavail,1,Playback(silence/1&im-sorry&number-not-answering&please-try-call-later&silence/1)
 same =>             n,Hangup()

exten => invalidinput,1,Playback(silence/1&im-sorry&cannot-complete-as-dialed&silence/1)
 same =>              n,Hangup()

; yukari: 001X
exten => 0011,5,Dial(PJSIP/yukari-phone,15)
exten => 0012,5,Dial(PJSIP/yukari-lpc,15)
exten => _001X,6,VoiceMail(0010,u)

; gensokyo home: 002X
exten => 0021,5,Dial(PJSIP/gensokyo-1,15)

; test: 99XX
exten => 9901,5,Dial(PJSIP/yukari-test,15)
exten => 9901,6,VoiceMail(9901,u)
exten => 9902,5,Dial(PJSIP/testmodem,15)
exten => 9903,5,Dial(PJSIP/testmodem2,15)

exten => 9910,5,NoOp()

same => n,Set(CALLERID_NUM=${CALLERID(num)})
same => n,Set(REAL_SRC=${CHANNEL(pjsip,remote_addr)})

same => n,Log(NOTICE, ENUM Verify Started for ${CALLERID_NUM} and ${REAL_SRC})
same => n,AGI(/etc/asterisk/agi/enum_verify.py,${CALLERID_NUM},${REAL_SRC})

same => n,Log(NOTICE, ENUM Verify Result: : ${ENUM_VERIFY_RESULT})
same => n,GotoIf($["${ENUM_VERIFY_RESULT}"="PASS"]?trusted)
same => n,GotoIf($["${ENUM_VERIFY_RESULT}"="NO_ENUM_RECORD"]?no_record)
same => n,GotoIf($["${ENUM_VERIFY_RESULT}"="SPOOFED"]?spoofed)

same => n,Log(NOTICE, ENUM Error)
same => n,Hangup(21)

same => n(trusted),Log(NOTICE, ENUM Verify Success)
same => n,Playback(silence/1&num-was-successfully)
same => n,Hangup()

same => n(spoofed),Log(NOTICE, ENUM Verify Failed)
same => n,Playback(silence/1&im-sorry)
same => n,Hangup(21)

same => n(no_record),Log(NOTICE, ENUM Verify Unknown (record not found))
same => n,Playback(silence/1&from-unknown-caller)
same => n,Hangup()

; program: 3XXX
exten => 3001,5,Playback(silence/1&your&number&is)
same  =>      n,SayAlpha(${CALLERID(num)})
same  =>      n,Playback(silence/1)

; fax and dialup: 4XXX
exten => 4001,5,Queue(faxs)

; special: 8XXX
exten => 8001,5,Answer()
 same =>      n,Set(CALLERID_NUM=${CALLERID(num)})
 same =>      n,GotoIf($["${CALLERID_NUM:0:8}" != "42400803"]?invalidinput,1:)
 same =>      n,VoiceMailMain(${CALLERID_NUM:8},s)

exten => _X!,5,Playback(silence/1&im-sorry&check-number-dial-again&silence/1)
 same =>      n,GotoIf($["${DIALSTATUS}" = "CHANUNAVAIL"]?chanunavail,1:)
