[ext-peer]

exten => sms,5,NoOp()

exten => _+04240803.,5,Goto(ext-peer-tolocal,${EXTEN:5:4}_${EXTEN:9},1)
exten => _+42400803.,5,Goto(ext-peer-tolocal,${EXTEN:5:4}_${EXTEN:9},1)
exten => _+04241331.,5,Goto(ext-peer-tolocal,${EXTEN:5:4}_${EXTEN:9},1)
exten => _+42401331.,5,Goto(ext-peer-tolocal,${EXTEN:5:4}_${EXTEN:9},1)

exten => _+X.,5,NoOp()
 same =>            n,Goto(ext-enum,${EXTEN},5)

; Catch Invalid
exten => _X!,5,Goto(ext-invalid,invalidinput,5)
exten => i,5,Goto(ext-invalid,invalidinput,5)

[ext-peer-tolocal]
exten => _XXXX_X.,1,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?skipanswer)
 same => n,Answer()
 same => n(skipanswer),GotoIf($["${EXTEN:5}" : ".*[^0-9]+.*"]?ext-invalid,invalidinput,5:)
 same => n,Goto(ext-local-${EXTEN:0:4},${EXTEN:5},5)
