[ext-invalid]

exten => i,5,Goto(invalidinput,5)
exten => t,5,Hangup()

exten => NOANSWER,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?msg)
 same => n,Playback(silence/1&number-not-answering&please-try-call-later&silence/1)
 same => n(msg),Hangup()

exten => BUSY,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?msg)
 same => n,Playback(silence/1&number&is-in-use&please-try-call-later&silence/1)
 same => n(msg),Hangup()

exten => CHANUNAVAIL,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?msg)
 same => n,Playback(silence/1&im-sorry&number-not-answering&please-try-call-later&silence/1)
 same => n(msg),Hangup()

exten => CONGESTION,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?msg)
 same => n,Playback(silence/1&all-circuits-busy-now&please-try-call-later&silence/1)
 same => n(msg),Hangup()

exten => CANCEL,5,Hangup()
exten => ANSWER,5,Hangup()

exten => unallocated,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?msg)
 same => n,Playback(silence/1&ss-noservice&silence/1)
 same => n(msg),Hangup()

exten => invalidinput,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?msg)
 same => n,Playback(silence/1&im-sorry&cannot-complete-as-dialed&check-number-dial-again&silence/1)
 same => n(msg),Hangup()

; fallbacks
exten => _X!,5,Goto(invalidinput,5)
exten => _+X!,5,Goto(invalidinput,5)
