[ext-local]

exten => fax,5,Queue(faxs)
 same => n,Hangup()

; yukari: 001X
exten => 0011,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 same => n,Dial(PJSIP/yukari-phone,15)
 same => n,VoiceMail(0010,u)
 same => n,Hangup()
 same => n(sms),GoSub(sub-sms-send,s,1(pjsip:yukari-phone))

exten => 0012,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 same => n,Dial(PJSIP/yukari-lpc,15)
 same => n,VoiceMail(0010,u)
 same => n,Hangup()
 same => n(sms),GoSub(sub-sms-send,s,1(pjsip:yukari-lpc))

exten => _001X,5,VoiceMail(0010,u)
 same => n,Hangup()

; gensokyo home: 002X
exten => 0021,5,Dial(PJSIP/gensokyo-1,15)
 same => n,Goto(ext-invalid,${DIALSTATUS},5)

; test: 99XX
exten => 9901,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 same => n,Dial(PJSIP/yukari-test,15)
 same => n,VoiceMail(9901,u)
 same => n,Hangup()
 same => n(sms),GoSub(sub-sms-send,s,1(pjsip:yukari-test))

exten => 9902,5,Dial(PJSIP/testmodem,15)
 same => n,Goto(ext-invalid,${DIALSTATUS},5)

exten => 9903,5,Dial(PJSIP/testmodem2,15)
 same => n,Goto(ext-invalid,${DIALSTATUS},5)

exten => 9910,5,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 same => n,Goto(ext-invalid,${DIALSTATUS},5)
 same => n(sms),GoSub(sub-sms-send,s,1(pjsip:webdemo))

; program: 3XXX
exten => 3001,5,Playback(silence/1&your&number&is)
 same => n,SayAlpha(${CALLERID(num)})
 same => n,Playback(silence/1)
 same => n,Hangup()

; fax and dialup: 4XXX
exten => 4001,5,Queue(faxs)
 same => n,Hangup()

; special: 8XXX
exten => 8001,5,Answer()
 same => n,Set(CALLERID_NUM=${CALLERID(num)})
 same => n,GotoIf($["${CALLERID_NUM:0:9}" = "+04240803"]?valid)
 same => n,Goto(ext-invalid,invalidinput,5)
 same => n(valid),VoiceMailMain(${CALLERID_NUM:9},s)
 same => n,Hangup()

; undefined ext
exten => _X!,5,Goto(ext-invalid,invalidinput,5)
exten => _+X!,5,Goto(ext-invalid,invalidinput,5)
