[ext-peer]

exten => sms,5,NoOp()

exten => _42400803.,5,Answer()
 same =>            n,GotoIf($["${EXTEN:8}" : ".*[^0-9]+.*"]?ext-local,invalidinput,1:)
 same =>            n,Goto(ext-local,${EXTEN:8},5)

exten => _42403618.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3618-jerry)

exten => _42403999.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3999-cowgl)

exten => _42400298.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-0298-hexp)

exten => _42402547.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-2547-lantian)

exten => _42403322.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3322-vconet)

;exten => _42401332.,5,NoOp()
; same =>            n,Dial(PJSIP/${EXTEN}@nu)

exten => _4240X.,5,NoOp()
 same => n,Set(TARGET_URI=${ENUMLOOKUP(${EXTEN},sip,,,e164.dn42)})
 same => n,Dial(PJSIP/peer-enum-outbound/sip:${TARGET_URI},30)
 same => n(done),Hangup()
