[ext-enum]

exten => _+042X.,5,NoOp()
 same => n,Set(TARGET_URI=${ENUMLOOKUP(${EXTEN},sip,,,tel.dn42)})
 same => n,Log(NOTICE, ENUM: ${EXTEN} -> ${TARGET_URI})
 same => n,GotoIf($["${TARGET_URI}"=""]?unallocated)
 same => n,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 same => n,Dial(PJSIP/peer-enum-outbound/sip:${TARGET_URI},60)
 same => n,Goto(ext-invalid,${DIALSTATUS},5)
 same => n(sms),GoSub(sub-sms-send,s,1(pjsip:peer-enum-outbound/sip:${TARGET_URI},sip:${TARGET_URI}))
 same => n(unallocated),Goto(ext-invalid,unallocated,5)

exten => _+424X.,5,NoOp()
 same => n,Set(TARGET_URI=${ENUMLOOKUP(${EXTEN},sip,,,e164.dn42)})
 same => n,Log(NOTICE, ENUM: ${EXTEN} -> ${TARGET_URI})
 same => n,GotoIf($["${TARGET_URI}"=""]?unallocated)
 same => n,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 same => n,Dial(PJSIP/peer-enum-outbound/sip:${TARGET_URI},60)
 same => n,Goto(ext-invalid,${DIALSTATUS},5)
 same => n(sms),GoSub(sub-sms-send,s,1(pjsip:peer-enum-outbound/sip:${TARGET_URI},sip:${TARGET_URI}))
 same => n(unallocated),Goto(ext-invalid,unallocated,5)

; Catch Invalid
exten => _X.,5,Goto(ext-invalid,invalidinput,5)
exten => _+X.,5,Goto(ext-invalid,invalidinput,5)
exten => i,5,Goto(ext-invalid,invalidinput,5)
