[ext-enum]

exten => _+0424X.,5,NoOp()
 same => n,Set(TARGET_URI=${ENUMLOOKUP(${EXTEN:1},sip,,,tel.dn42)})
 same => n,GotoIf($["${TARGET_URI}"=""]?done)
 same => n,Dial(PJSIP/peer-enum-outbound/sip:${TARGET_URI},30)
 same => n(done),Hangup()

exten => _+4240X.,5,NoOp()
 same => n,Set(TARGET_URI=${ENUMLOOKUP(${EXTEN:1},sip,,,e164.dn42)})
 same => n,GotoIf($["${TARGET_URI}"=""]?done)
 same => n,Dial(PJSIP/peer-enum-outbound/sip:${TARGET_URI},30)
 same => n(done),Hangup()
