[ext-peer]

exten => sms,5,NoOp()

exten => _+04240803.,5,Answer()
 same =>            n,GotoIf($["${EXTEN:9}" : ".*[^0-9]+.*"]?ext-local,invalidinput,1:)
 same =>            n,Goto(ext-local,${EXTEN:9},5)
exten => _+42400803.,5,Answer()
 same =>            n,GotoIf($["${EXTEN:9}" : ".*[^0-9]+.*"]?ext-local,invalidinput,1:)
 same =>            n,Goto(ext-local,${EXTEN:9},5)

exten => _+04243618.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3618-jerry)
exten => _+42403618.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3618-jerry)

exten => _+04243999.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3999-cowgl)
exten => _+42403999.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3999-cowgl)

exten => _+04240298.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-0298-hexp)
exten => _+42400298.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-0298-hexp)

exten => _+04242547.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-2547-lantian)
exten => _+42402547.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-2547-lantian)

exten => _+04243322.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3322-vconet)
exten => _+42403322.,5,NoOp()
 same =>            n,Dial(PJSIP/${EXTEN}@peer-3322-vconet)

exten => _+X.,5,NoOp()
 same =>            n,Goto(ext-enum,${EXTEN},5)
