[sms]

exten => _+0424XXXX.,1,Verbose(2, "Text User, To: ${MESSAGE(to)}, Hint: ${ARG1}, From: ${MESSAGE(from)}, CID: ${CALLERID(all)}, Body: ${MESSAGE(body)}")
 same =>            n,Set(FROM_PEER=${CUT(MESSAGE(from),:,2)})
 same =>            n,Set(FROM_PEER=${CUT(FROM_PEER,@,1)})
 same =>            n,Set(MESSAGE(from)=${PJSIP_ENDPOINT(${FROM_PEER},callerid)})
 same =>            n,Goto(ext-peer-sms,${EXTEN},5)

; invalid
exten => _X!,1,Goto(ext-invalid-sms,invalidinput,5)

[ext-peer-sms]
exten => _+04240803.,5,NoOp()
 same =>            n,GotoIf($["${EXTEN:9}" : ".*[^0-9]+.*"]?ext-invalid-sms,invalidinput,5:)
 same =>            n,Goto(ext-local-sms,${EXTEN:9},5)

exten => _+42400803.,5,NoOp()
 same =>            n,GotoIf($["${EXTEN:9}" : ".*[^0-9]+.*"]?ext-invalid-sms,invalidinput,5:)
 same =>            n,Goto(ext-local-sms,${EXTEN:9},5)

; invalid
exten => _X!,5,Goto(ext-invalid-sms,invalidinput,5)

[ext-local-sms]

; yukari: 001X
exten => 0011,5,MessageSend(pjsip:yukari-phone)
exten => 0012,5,MessageSend(pjsip:yukari-lpc)

exten => 9901,5,MessageSend(pjsip:yukari-test)
exten => 9910,5,MessageSend(pjsip:webdemo)

; invalid
exten => _X!,5,Goto(ext-invalid-sms,invalidinput,5)

[ext-invalid-sms]
exten => i,5,Hangup()
exten => invalidinput,5,Hangup()
exten => _X!,5,Hangup()
