[sub-sms-send]

exten => s,1,Set(MESSAGE(from)="${CALLERID(name)}" <sip:${CALLERID(num)}@pbx.gensokyo.dn42>)
 same => n,MessageSend(${ARG1})
 same => n,GotoIf($["${MESSAGE_SEND_STATUS}"!="SUCCESS"]?ext-invalid,invalidinput,5)
 same => n,Hangup()
