[sub-sms-send]

exten => s,1,NoOp()

 ; pjsip: to sip:
 same => n,Set(MESSAGE(to)=${IF($["${MESSAGE(to):0:6}"="pjsip:"]?${MESSAGE(to)}:sip:${MESSAGE(to):6})})

 same => n,MessageSend(${ARG1})
 same => n,GotoIf($["${MESSAGE_SEND_STATUS}"!="SUCCESS"]?ext-invalid,invalidinput,5)
 same => n,Hangup()
