[sub-sms-send]

; arg1: send dest
; arg2: override to

exten => s,1,NoOp()

 ; MESSAGE to: force from arg2
 same => n,GotoIf($[${ISNULL(${ARG2})}]?skip_forceto)
 same => n,Set(MESSAGE(to)=<${ARG2}>)

 ; MESSAGE to: pjsip: to sip:
 same => n(skip_forceto),GotoIf($["${MESSAGE(to):0:6}"!="pjsip:"]?skip_pjsip)
 same => n,Set(MESSAGE(to)=${MESSAGE(to):2})
 same => n(skip_pjsip),NoOp()

 ; MESSAGE from: reverse search for endpoint
 same => n,Set(URI_PART=${CUT(MESSAGE(from),<,2)})
 same => n,Set(URI_PART=${CUT(URI_PART,>,1)})
 same => n,Set(URI_USER=${CUT(URI_PART,@,1)})
 same => n,Set(SENDER_ENDPOINT=${CUT(URI_USER,:,2)})

 same => n,Set(ENDPOINT_CID=${PJSIP_ENDPOINT(${SENDER_ENDPOINT},callerid)})

 same => n,Set(CALLERID(all)=${ENDPOINT_CID})
 same => n,ExecIf($["${CALLERID(num)}" = ""]?Set(CALLERID(num)=${SENDER_ENDPOINT}))

 same => n,Set(MESSAGE(from)="${CALLERID(name)}" <sip:${CALLERID(num)}@pbx.gensokyo.dn42>)

 same => n,MessageSend(${ARG1})
 same => n,GotoIf($["${MESSAGE_SEND_STATUS}"!="SUCCESS"]?ext-invalid,invalidinput,5)
 same => n,Hangup()
