[sub-sms-send]
; ARG1: send dest
; ARG2: override Message(to)

exten => s,1,NoOp()

 ; MESSAGE to: force from arg2
 same => n,GotoIf($[${ISNULL(${ARG2})}]?skip_forceto)
 same => n,Set(MESSAGE(to)=<${ARG2}>)

 ; MESSAGE to: pjsip: to sip:
 same => n(skip_forceto),GotoIf($["${MESSAGE(to):0:6}"!="pjsip:"]?skip_pjsip)
 same => n,Set(MESSAGE(to)=${MESSAGE(to):2})
 same => n(skip_pjsip),NoOp()

 ; extract user (endpoint or number) from MESSAGE(from)
 same => n,GoSub(sub-utils-extract-user,s,1(${MESSAGE(from)}))
 same => n,Set(SENDER_USER=${SUB_UTILS_EXTRACT_USER_RESULT})

 ; check if is local or remote
 same => n,Set(ENDPOINT_CID=${PJSIP_ENDPOINT(${SENDER_USER},callerid)})
 same => n,GotoIf(${ISNULL(${ENDPOINT_CID})}?from_remote:from_local)

 ; (from local) MESSAGE from: reverse search for endpoint
 same => n(from_local),Set(CALLERID(all)=${ENDPOINT_CID})
 same => n,Goto(do_send)

 ; (from remote) MESSAGE from: use it as-is
 same => n(from_remote),Set(CALLERID(num)=${SENDER_USER})
 same => n,Goto(do_send)

 same => n(do_send),GotoIf($["${CALLERID(num)}" = ""]?ext-invalid,invalidinput,5)
 same => n,Set(MESSAGE(from)="${CALLERID(name)}" <sip:${CALLERID(num)}@pbx.gensokyo.dn42>)
 same => n,MessageSend(${ARG1})
 same => n,GotoIf($["${MESSAGE_SEND_STATUS}"!="SUCCESS"]?ext-invalid,invalidinput,5)
 same => n,Hangup()
