[sub-utils-extract-user]
; ARG1: "xxx <{sip,pjsip,iax,...}:{username}@{domain,ip}:{port}>;{args}"

exten => s,1,NoOp()
 same => n,Set(URI_PART=${CUT(ARG1,<,2)})
 same => n,Set(URI_PART=${CUT(URI_PART,>,1)})
 same => n,Set(URI_USER=${CUT(URI_PART,@,1)})
 same => n,Set(SUB_UTILS_EXTRACT_USER_RESULT=${CUT(URI_USER,:,2)})
 same => n,Return()
