[sub-dial]
; ARG1: dial target
; ARG2: message target (optional)
; ARG3: voicemail target (optional)
; ARG4: timeout (default 15)
; ARG5: early media / moh class (optional)

exten => s,1,Set(DIAL_TIMEOUT=${IF($["${ARG4}"=""]?15:${ARG4})})
 ; direct sms jump
 same => n,GotoIf($["${CHANNEL(channeltype)}" = "Message"]?sms)
 ; early media args
 same => n,ExecIf($["${ARG5}" != ""]?Progress())
 same => n,Set(DIAL_OPTS=${IF($["${ARG5}" != ""]?m(${ARG5}):)})
 ; dial
 same => n,Dial(${ARG1},${DIAL_TIMEOUT},${DIAL_OPTS})
 ; voice mail
 same => n,GotoIf($["${ARG3}" = ""]?novm)
 same => n,VoiceMail(${ARG3},u)
 ; fallback
 same => n,Hangup()
 same => n(novm),Goto(ext-invalid,${DIALSTATUS},5)
; sms target
 same => n(sms),GotoIf($["${ARG2}" = ""]?ext-invalid,invalidinput,5)
 same => n,GoSub(sub-sms-send,s,1(${ARG2}))
 same => n,Hangup()
