[pstn-voipms](peer-template-endpoint)
aors = pstn-voipms
;auth = voipms
context = context-pstn
outbound_auth = voipms
; NAT parameters:
rtp_symmetric = yes
rewrite_contact = yes
send_rpid = yes
from_user = 426424
accountcode=remove-pstn

[pstn-voipms](peer-template-aor)
contact = sip:426424@paris1.voip.ms

[pstn-voipms]
type = identify
endpoint = pstn-voipms
match = paris1.voip.ms
match = 208.100.60.0/24

[pstn-voipms]
type = registration
outbound_auth = voipms
client_uri = sip:426424@paris1.voip.ms:5060
server_uri = sip:paris1.voip.ms:5060
