[ivr-sstv-qsl]

exten => s,1,Answer()
 same => n,Set(MAX_DIGITS=2)
 same => n,Set(TIMEOUT=5000)
 same => n,Playback(silence/1)
 same => n,AGI(/usr/local/bin/tel42edgetts,-ivr,-ivr-mode,hash,"Welcome to Gensokyo SSTV Confirmation of Contact. Please use two digits to select the encoding mode: 00: martin1, 01: martin2, 02: scottie1, 03: scottie2, 04: robot36, 05: robot72, 06: pd50, 07: pd90, 08: pd120, 09: pd160, 10: pd180, 11: pd240, 12: pd290. Enter two digits and press hash to confirm.")

 same => n,Goto(ivr-sstv-qsl,process-${TTS_USERINPUT},1)
 same => n,Goto(ivr-sstv-qsl,invalid,1)

exten => process-00,1,Set(SSTV_MODE=martin1)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-01,1,Set(SSTV_MODE=martin2)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-02,1,Set(SSTV_MODE=scottie1)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-03,1,Set(SSTV_MODE=scottie2)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-04,1,Set(SSTV_MODE=robot36)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-05,1,Set(SSTV_MODE=robot72)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-06,1,Set(SSTV_MODE=pd50)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-07,1,Set(SSTV_MODE=pd90)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-08,1,Set(SSTV_MODE=pd120)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-09,1,Set(SSTV_MODE=pd160)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-10,1,Set(SSTV_MODE=pd180)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-11,1,Set(SSTV_MODE=pd240)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => process-12,1,Set(SSTV_MODE=pd290)
 same => n,Goto(ivr-sstv-qsl-send,1)

exten => ivr-sstv-qsl-send,1,NoOp()
 same => n,Playback(silence/1)
 same => n,AGI(/usr/local/bin/tel42edgetts,"You have selected ${SSTV_MODE} mode. Sending SSTV image.")
 same => n,Set(PJSIP_MEDIA_OFFER(audio)=ulaw,alaw)
 same => n,Set(PJSIP_SEND_SESSION_REFRESH()=invite)
 same => n,Wait(0.5)
 same => n,AGI(/usr/local/bin/tel42sstv,-b,/etc/tel42sstv/gensokyo-qsl.svg,--play,--caller,${CALLERID(num)},--callee,+042408033201,-f,${SSTV_MODE},--sample-rate,16000)
 same => n,Hangup()

exten => invalid,1,AGI(/usr/local/bin/tel42edgetts,"Invalid input. Please try again.")
 same => n,Goto(s,1)

exten => t,1,AGI(/usr/local/bin/tel42edgetts,"Input timeout. Please try again.")
 same => n,Goto(s,1)
