[ivr-anti-fool]
exten => s,1,Answer
;same => n,Wait(1)

same => n,Set(DIR=/var/lib/asterisk/sounds/anti-fool)

same => n(main-menu),SendDTMF(0,0.5)
same => n,Background(${DIR}/welcome&${DIR}/main-menu)
same => n,WaitExten(10)

exten => 1,1,Read(vKey,${DIR}/gl-ml-gml,1,,,3)
same => n,Goto(s,main-menu)

exten => 2,1,Read(vKey,${DIR}/mc,1,,,3)
same => n,Goto(s,main-menu)

exten => 3,1,Goto(ivr-anti-fool-3,s,1)

exten => _[0#],1,Read(vKey,${DIR}/xp-gf,1,,,3)
same => n,Goto(s,main-menu)

exten => i,1,Read(vKey,${DIR}/nbatlcpa,1,,,0.5)
same => n,Goto(s,main-menu)

exten => t,1,Goto(s,main-menu)


[ivr-anti-fool-3]
exten => s,1(main-menu),Background(${DIR}/njjzw-menu&${DIR}/xsz&${DIR}/qa1&${DIR}/xsl&${DIR}/qa2)
same => n,WaitExten(10)

exten => 1,1,Read(vKey,${DIR}/xsz-answer,1,,,3)
same => n,Goto(s,main-menu)

exten => 2,1,Read(vKey,${DIR}/xsl-answer,1,,,3)
same => n,Goto(s,main-menu)

exten => *,1,Goto(ivr-anti-fool,s,main-menu)

exten => i,1,Goto(s,main-menu)

exten => t,1,Goto(s,main-menu)
