[ivr-pstn]

exten => s,1,Wait(1)
 same => n(loop),Background(/etc/asterisk-sounds/ivr-pstn-intro)
 same => n,WaitExten(15)

exten => fax,1,Queue(faxs)

exten => i,1,Playback(silence/1&im-sorry&cannot-complete-as-dialed&silence/1)
 same => n,Goto(s,loop)

exten => t,1,Goto(s,loop)

exten => _X,1,Wait(1)
 same => n,GoSub(${EXTEN},100)
 same => n,Wait(1)
 same => n,Goto(s,loop)

exten => 1,100,Playback(your&number&is)
 same => n,SayAlpha(${CALLERID(num)})
 same => n,Return()

exten => 2,100,Goto(ivr-pstn-dial42,s,1)

[ivr-pstn-dial42]

exten => s,1,Playback(silence/1)
 same => n,Set(USERINPUT=)
 same => n,Read(USERINPUT,/etc/asterisk-sounds/ivr-pstn-dial42,18,,1,4)
 same => n,GotoIf($["${READSTATUS}" = "TIMEOUT" & "${USERINPUT}" = ""]?s,1:)
 same => n,GotoIf($["${USERINPUT}" = ""]?ivr-pstn,${EXTEN},s:dial42,1)

exten => dial42,1,Set(CALLERID(all)="Gensokyo Tele42 Proxy for ${CALLERID(num)}" <+042408038100>)
 same => n,Log(DEBUG, proxying to ${USERINPUT})
 same => n,Set(DEST=${USERINPUT})
 same => n,ExecIf($["${DEST:0:3}" = "042"]?Set(DEST=+${DEST}))
 same => n,ExecIf($["${DEST:0:4}" = "4240"]?Set(DEST=+${DEST}))
 same => n,ExecIf($["${DEST:0:1}" != "+"]?Set(DEST=+042${DEST}))
 same => n,Goto(ext-peer,${DEST},5)

exten => i,1,Playback(silence/1&im-sorry&cannot-complete-as-dialed&silence/1)
 same => n,Goto(s,1)
