[phone-template-endpoint](!)
type=endpoint
context=context-local
allow=!all,opus,g722,speex,g726,ulaw,alaw,vp9,h265,vp8,h264
rtp_symmetric=no
rewrite_contact=yes
direct_media=no
rtp_ipv6=yes
tone_zone=cn
rtp_timeout=60
rtp_timeout_hold=120
rpid_immediate=yes
force_rport=yes
rewrite_contact=yes
trust_id_inbound=yes
trust_id_outbound=yes
send_pai=yes
send_rpid=yes

[phone-template-auth](!)
type=auth

[phone-template-aor](!)
type=aor
max_contacts=2
remove_existing=yes
