[webrtc-template-endpoint](!)
type=endpoint
context=context-local
allow=!all,opus,ulaw,alaw
dtls_auto_generate_cert=yes
webrtc=yes

[webrtc-template-auth](!)
type=auth

[webrtc-template-aor](!)
type=aor
max_contacts=1
remove_existing=yes
