[webrtc-template-endpoint](!)
type=endpoint
context=context-local
allow=!all,opus,g722,speex,g726,ulaw,alaw,vp9,h265,vp8,h264
max_video_streams=1
dtls_auto_generate_cert=yes
webrtc=yes
transport=transport-wss

[webrtc-template-auth](!)
type=auth

[webrtc-template-aor](!)
type=aor
max_contacts=1
remove_existing=yes
